// The contract between a witness and the machines that verify for it.
//
// This file is the specification. Prose in a README is a poor protocol
// definition for anything a third party might implement, and the point of this
// channel is that other people's machines can join it.
//
// # What a worker is trusted with, which is almost nothing
//
// A worker reports that an epoch verified. It cannot be believed on that alone:
// the operator's signed root is public, so a worker that did no work can still
// report the correct answer. Everything below is shaped by that.
//
//   - Assignments carry a nonce that must be echoed, so a result answers one
//     dispatch and an older honest result cannot be replayed as new work.
//   - Results outside the assigned range are refused.
//   - An expired lease returns its range to the queue with a FRESH nonce, so an
//     abandoned worker's late reply cannot answer the reissue.
//   - Nothing a worker says produces a misbehaviour finding. A disagreement
//     means the witness re-runs the epoch itself, and its own answer decides.
//
// A hostile worker can waste dispatch and inflate a coverage figure until it is
// spot-checked. It cannot make this witness accuse an operator.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.36.1
// source: proto/work.proto

package workpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_Result
	//	*WorkerMessage_Progress
	//	*WorkerMessage_Capacity
	//	*WorkerMessage_Want
	Msg           isWorkerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_proto_work_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_proto_work_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetMsg() isWorkerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetResult() *Result {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *WorkerMessage) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *WorkerMessage) GetCapacity() *Capacity {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Capacity); ok {
			return x.Capacity
		}
	}
	return nil
}

func (x *WorkerMessage) GetWant() *Want {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Want); ok {
			return x.Want
		}
	}
	return nil
}

type isWorkerMessage_Msg interface {
	isWorkerMessage_Msg()
}

type WorkerMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

type WorkerMessage_Progress struct {
	Progress *Progress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type WorkerMessage_Capacity struct {
	Capacity *Capacity `protobuf:"bytes,4,opt,name=capacity,proto3,oneof"`
}

type WorkerMessage_Want struct {
	Want *Want `protobuf:"bytes,5,opt,name=want,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Msg() {}

func (*WorkerMessage_Result) isWorkerMessage_Msg() {}

func (*WorkerMessage_Progress) isWorkerMessage_Msg() {}

func (*WorkerMessage_Capacity) isWorkerMessage_Msg() {}

func (*WorkerMessage_Want) isWorkerMessage_Msg() {}

type WitnessMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WitnessMessage_Assignment
	//	*WitnessMessage_Ack
	Msg           isWitnessMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WitnessMessage) Reset() {
	*x = WitnessMessage{}
	mi := &file_proto_work_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WitnessMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WitnessMessage) ProtoMessage() {}

func (x *WitnessMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WitnessMessage.ProtoReflect.Descriptor instead.
func (*WitnessMessage) Descriptor() ([]byte, []int) {
	return file_proto_work_proto_rawDescGZIP(), []int{1}
}

func (x *WitnessMessage) GetMsg() isWitnessMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WitnessMessage) GetAssignment() *Assignment {
	if x != nil {
		if x, ok := x.Msg.(*WitnessMessage_Assignment); ok {
			return x.Assignment
		}
	}
	return nil
}

func (x *WitnessMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*WitnessMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isWitnessMessage_Msg interface {
	isWitnessMessage_Msg()
}

type WitnessMessage_Assignment struct {
	Assignment *Assignment `protobuf:"bytes,1,opt,name=assignment,proto3,oneof"`
}

type WitnessMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*WitnessMessage_Assignment) isWitnessMessage_Msg() {}

func (*WitnessMessage_Ack) isWitnessMessage_Msg() {}

// Hello opens the session. It must be the first message.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Origins this worker has a verifier for. A worker handed work it cannot do
	// reports every epoch unavailable, which from the witness's side is
	// indistinguishable from the log being down — so it is asked rather than
	// assumed.
	Origins []string `protobuf:"bytes,2,rep,name=origins,proto3" json:"origins,omitempty"`
	// How many epochs it will work on at once. The opening Want, in effect: the
	// witness sizes the first assignment from it, and everything after that comes
	// from Want messages as capacity frees up.
	Parallel int32 `protobuf:"varint,3,opt,name=parallel,proto3" json:"parallel,omitempty"`
	// Free-text, for the operator's own benefit when something looks wrong.
	Version  string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Platform string `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	// The protocol this worker speaks. A session whose protocol differs from the
	// witness's is refused, loudly, rather than served.
	//
	// This exists because a stale worker is not a worker that fails: protobuf
	// fields are positional, so an old build's `root` arrives in the field now
	// called `computed_prev_root` and the witness records the resulting mismatch
	// as a fact about the LOG. Two workers running a build one commit old wrote
	// roughly 3,300 false "unverified" epochs that way, which is a false hole in
	// the coverage — the one number this witness must not get wrong in that
	// direction. Refusing the session costs a restart; accepting it corrupts the
	// record silently.
	Protocol      int32 `protobuf:"varint,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_work_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_work_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hello) GetOrigins() []string {
	if x != nil {
		return x.Origins
	}
	return nil
}

func (x *Hello) GetParallel() int32 {
	if x != nil {
		return x.Parallel
	}
	return 0
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Hello) GetProtocol() int32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

// Want asks for more work, and is what makes this channel pull rather than push.
//
// The witness used to decide when to send: it leased a range, pushed it, and
// then blocked until that range came back in full before leasing another. So
// every worker held exactly one range at a time, whatever it was — a forty-core
// box and a laptop got the same thing — and the pipeline drained completely at
// every boundary while the last epoch finished and an ack round-tripped.
// Measured on a laptop: twenty-three seconds between ranges of twelve epochs it
// could work eight at a time.
//
// The worker knows its own capacity and always did; it reports it in Hello and
// in Capacity, and for a long time the witness only logged it. Now it asks.
//
// Epochs is how many MORE this worker can take on top of what it already holds.
// It is a request, not a reservation: the witness may send fewer, or nothing,
// and the worker asks again when it has room. Asking for more than can be
// finished inside a lease is self-defeating rather than dangerous — the surplus
// expires and is handed to somebody else.
type Want struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epochs        int32                  `protobuf:"varint,1,opt,name=epochs,proto3" json:"epochs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Want) Reset() {
	*x = Want{}
	mi := &file_proto_work_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Want) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Want) ProtoMessage() {}

func (x *Want) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Want.ProtoReflect.Descriptor instead.
func (*Want) Descriptor() ([]byte, []int) {
	return file_proto_work_proto_rawDescGZIP(), []int{3}
}

func (x *Want) GetEpochs() int32 {
	if x != nil {
		return x.Epochs
	}
	return 0
}

// Assignment is a contiguous range of epochs on one log.
type Assignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where to fetch the proof, when the witness wants to choose.
	//
	// Normally empty: a worker builds the URL from the operator's log directory
	// and fetches from the operator, which is the arrangement that makes its
	// verdict worth having — it checks the proof against roots it resolved
	// itself, from the source, not against anything this witness asserted.
	//
	// When the witness serves proofs, this is set on EVERY assignment, and the
	// worker fetches {base}/proof/{origin}/{epoch}. One proof in a hundred that
	// it serves has a bit flipped, and the worker must reject those — which only
	// tests anything because it cannot tell which ones they are.
	//
	// An earlier version set this only for the corrupted ones, which labelled
	// them: a worker had merely to refuse anything coming from the witness to
	// score perfectly while verifying nothing. A test the subject can identify
	// is not a test.
	//
	// The roots are still resolved by the worker from the operator, never taken
	// from here. Serving the bytes lets the witness test a worker; it does not
	// let it make one agree.
	ProofBase string `protobuf:"bytes,7,opt,name=proof_base,json=proofBase,proto3" json:"proof_base,omitempty"`
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Origin    string `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	From      int64  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To        int64  `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	// Echoed in every result for this assignment.
	Nonce string `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Unix seconds. Past it the lease is void: results will be refused and the
	// range may already belong to somebody else, so a worker should stop rather
	// than finish.
	DeadlineUnix  int64 `protobuf:"varint,6,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_proto_work_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_proto_work_proto_rawDescGZIP(), []int{4}
}

func (x *Assignment) GetProofBase() string {
	if x != nil {
		return x.ProofBase
	}
	return ""
}

func (x *Assignment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Assignment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Assignment) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Assignment) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Assignment) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *Assignment) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

type Result struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	Nonce        string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Origin       string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Epoch        int64                  `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// The two roots the worker COMPUTED from the proof, and nothing else.
	//
	// It is never told what the operator published, and it does not report a
	// verdict. That is not a division of labour, it is what makes the answer
	// worth having: a worker that does not know the expected value cannot report
	// it without doing the work, so fabrication stops being something to sample
	// for and becomes something that cannot happen.
	//
	// The witness holds the published roots and does the comparison. A worker
	// that computes wrong roots produces a mismatch, which the witness resolves
	// by re-verifying the epoch itself — it can waste our time, and it cannot
	// make us believe anything.
	ComputedPrevRoot string `protobuf:"bytes,6,opt,name=computed_prev_root,json=computedPrevRoot,proto3" json:"computed_prev_root,omitempty"`
	ComputedCurrRoot string `protobuf:"bytes,7,opt,name=computed_curr_root,json=computedCurrRoot,proto3" json:"computed_curr_root,omitempty"`
	Worker           string `protobuf:"bytes,8,opt,name=worker,proto3" json:"worker,omitempty"`
	DurationMs       int64  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Set when the epoch could not be verified. Not a finding: an epoch that
	// could not be fetched is unavailable, not evidence of anything.
	Error         string `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_work_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_work_proto_rawDescGZIP(), []int{5}
}

func (x *Result) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Result) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *Result) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Result) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Result) GetComputedPrevRoot() string {
	if x != nil {
		return x.ComputedPrevRoot
	}
	return ""
}

func (x *Result) GetComputedCurrRoot() string {
	if x != nil {
		return x.ComputedCurrRoot
	}
	return ""
}

func (x *Result) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

func (x *Result) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Progress lets a long assignment say it is still alive, so a slow worker is
// distinguishable from a dead one before its lease expires.
type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId  string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_proto_work_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_proto_work_proto_rawDescGZIP(), []int{6}
}

func (x *Progress) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Progress) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

// Capacity is what a worker can currently do, sent periodically and unprompted.
//
// The witness cannot infer this. It sees results arriving and cannot tell a
// laptop that has been closed from one whose owner is compiling something, or a
// machine that is yielding correctly from one that is broken — and those want
// opposite responses. A worker that says "I am down to one at a time because my
// owner came back" is reporting a healthy system doing what it was built to do.
//
// Capacity is for the operator to look at; Want is what actually schedules.
// They are deliberately separate: this one is a description of the machine and
// is sent on a timer whether or not there is work, so a fleet that has gone
// quiet is still legible. Conflating them would mean an idle worker stopped
// reporting at exactly the moment its state became interesting.
type Capacity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How many epochs this worker will run at once, right now. Its own
	// measurement of itself, not a configured maximum.
	Parallel int32 `protobuf:"varint,1,opt,name=parallel,proto3" json:"parallel,omitempty"`
	// Cores the worker believes are in use across its whole machine, and the
	// ceiling it is holding itself to. Both in cores, both as the worker
	// measures them — two machines will not agree on what a core is, and that is
	// fine: the interesting shape is each machine against its own budget.
	LoadCores   float64 `protobuf:"fixed64,2,opt,name=load_cores,json=loadCores,proto3" json:"load_cores,omitempty"`
	BudgetCores float64 `protobuf:"fixed64,3,opt,name=budget_cores,json=budgetCores,proto3" json:"budget_cores,omitempty"`
	// Logical CPUs the worker may use. On a Mac in background QoS this is the
	// efficiency-core count, not the machine's core count, and the difference is
	// the whole point of running there.
	Cpus          int32 `protobuf:"varint,4,opt,name=cpus,proto3" json:"cpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capacity) Reset() {
	*x = Capacity{}
	mi := &file_proto_work_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capacity) ProtoMessage() {}

func (x *Capacity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capacity.ProtoReflect.Descriptor instead.
func (*Capacity) Descriptor() ([]byte, []int) {
	return file_proto_work_proto_rawDescGZIP(), []int{7}
}

func (x *Capacity) GetParallel() int32 {
	if x != nil {
		return x.Parallel
	}
	return 0
}

func (x *Capacity) GetLoadCores() float64 {
	if x != nil {
		return x.LoadCores
	}
	return 0
}

func (x *Capacity) GetBudgetCores() float64 {
	if x != nil {
		return x.BudgetCores
	}
	return 0
}

func (x *Capacity) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

type Ack struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AssignmentId string                 `protobuf:"bytes,1,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	Epoch        int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Accepted     bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Why not, when it was refused. Sent so a misbehaving or misconfigured worker
	// can be diagnosed from its own logs rather than only from the witness's.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_work_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_work_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_work_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Ack) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Ack) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *Ack) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_work_proto protoreflect.FileDescriptor

const file_proto_work_proto_rawDesc = "" +
	"\n" +
	"\x10proto/work.proto\x12\x11ktwitness.work.v1\"\xa2\x02\n" +
	"\rWorkerMessage\x120\n" +
	"\x05hello\x18\x01 \x01(\v2\x18.ktwitness.work.v1.HelloH\x00R\x05hello\x123\n" +
	"\x06result\x18\x02 \x01(\v2\x19.ktwitness.work.v1.ResultH\x00R\x06result\x129\n" +
	"\bprogress\x18\x03 \x01(\v2\x1b.ktwitness.work.v1.ProgressH\x00R\bprogress\x129\n" +
	"\bcapacity\x18\x04 \x01(\v2\x1b.ktwitness.work.v1.CapacityH\x00R\bcapacity\x12-\n" +
	"\x04want\x18\x05 \x01(\v2\x17.ktwitness.work.v1.WantH\x00R\x04wantB\x05\n" +
	"\x03msg\"\x84\x01\n" +
	"\x0eWitnessMessage\x12?\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2\x1d.ktwitness.work.v1.AssignmentH\x00R\n" +
	"assignment\x12*\n" +
	"\x03ack\x18\x02 \x01(\v2\x16.ktwitness.work.v1.AckH\x00R\x03ackB\x05\n" +
	"\x03msg\"\xa3\x01\n" +
	"\x05Hello\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aorigins\x18\x02 \x03(\tR\aorigins\x12\x1a\n" +
	"\bparallel\x18\x03 \x01(\x05R\bparallel\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\x05R\bprotocol\"\x1e\n" +
	"\x04Want\x12\x16\n" +
	"\x06epochs\x18\x01 \x01(\x05R\x06epochs\"\xcb\x01\n" +
	"\n" +
	"Assignment\x12\x1d\n" +
	"\n" +
	"proof_base\x18\a \x01(\tR\tproofBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\x03R\x02to\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\tR\x05nonce\x12#\n" +
	"\rdeadline_unix\x18\x06 \x01(\x03R\fdeadlineUnixJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"R\x04stepR\x05block\"\x9c\x02\n" +
	"\x06Result\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x03R\x05epoch\x12,\n" +
	"\x12computed_prev_root\x18\x06 \x01(\tR\x10computedPrevRoot\x12,\n" +
	"\x12computed_curr_root\x18\a \x01(\tR\x10computedCurrRoot\x12\x16\n" +
	"\x06worker\x18\b \x01(\tR\x06worker\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"E\n" +
	"\bProgress\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\"|\n" +
	"\bCapacity\x12\x1a\n" +
	"\bparallel\x18\x01 \x01(\x05R\bparallel\x12\x1d\n" +
	"\n" +
	"load_cores\x18\x02 \x01(\x01R\tloadCores\x12!\n" +
	"\fbudget_cores\x18\x03 \x01(\x01R\vbudgetCores\x12\x12\n" +
	"\x04cpus\x18\x04 \x01(\x05R\x04cpus\"t\n" +
	"\x03Ack\x12#\n" +
	"\rassignment_id\x18\x01 \x01(\tR\fassignmentId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason2Z\n" +
	"\x04Work\x12R\n" +
	"\aSession\x12 .ktwitness.work.v1.WorkerMessage\x1a!.ktwitness.work.v1.WitnessMessage(\x010\x01B:Z8github.com/gdbsecurity/kt-witness/internal/workpb;workpbb\x06proto3"

var (
	file_proto_work_proto_rawDescOnce sync.Once
	file_proto_work_proto_rawDescData []byte
)

func file_proto_work_proto_rawDescGZIP() []byte {
	file_proto_work_proto_rawDescOnce.Do(func() {
		file_proto_work_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_work_proto_rawDesc), len(file_proto_work_proto_rawDesc)))
	})
	return file_proto_work_proto_rawDescData
}

var file_proto_work_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_work_proto_goTypes = []any{
	(*WorkerMessage)(nil),  // 0: ktwitness.work.v1.WorkerMessage
	(*WitnessMessage)(nil), // 1: ktwitness.work.v1.WitnessMessage
	(*Hello)(nil),          // 2: ktwitness.work.v1.Hello
	(*Want)(nil),           // 3: ktwitness.work.v1.Want
	(*Assignment)(nil),     // 4: ktwitness.work.v1.Assignment
	(*Result)(nil),         // 5: ktwitness.work.v1.Result
	(*Progress)(nil),       // 6: ktwitness.work.v1.Progress
	(*Capacity)(nil),       // 7: ktwitness.work.v1.Capacity
	(*Ack)(nil),            // 8: ktwitness.work.v1.Ack
}
var file_proto_work_proto_depIdxs = []int32{
	2, // 0: ktwitness.work.v1.WorkerMessage.hello:type_name -> ktwitness.work.v1.Hello
	5, // 1: ktwitness.work.v1.WorkerMessage.result:type_name -> ktwitness.work.v1.Result
	6, // 2: ktwitness.work.v1.WorkerMessage.progress:type_name -> ktwitness.work.v1.Progress
	7, // 3: ktwitness.work.v1.WorkerMessage.capacity:type_name -> ktwitness.work.v1.Capacity
	3, // 4: ktwitness.work.v1.WorkerMessage.want:type_name -> ktwitness.work.v1.Want
	4, // 5: ktwitness.work.v1.WitnessMessage.assignment:type_name -> ktwitness.work.v1.Assignment
	8, // 6: ktwitness.work.v1.WitnessMessage.ack:type_name -> ktwitness.work.v1.Ack
	0, // 7: ktwitness.work.v1.Work.Session:input_type -> ktwitness.work.v1.WorkerMessage
	1, // 8: ktwitness.work.v1.Work.Session:output_type -> ktwitness.work.v1.WitnessMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_work_proto_init() }
func file_proto_work_proto_init() {
	if File_proto_work_proto != nil {
		return
	}
	file_proto_work_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_Result)(nil),
		(*WorkerMessage_Progress)(nil),
		(*WorkerMessage_Capacity)(nil),
		(*WorkerMessage_Want)(nil),
	}
	file_proto_work_proto_msgTypes[1].OneofWrappers = []any{
		(*WitnessMessage_Assignment)(nil),
		(*WitnessMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_work_proto_rawDesc), len(file_proto_work_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_work_proto_goTypes,
		DependencyIndexes: file_proto_work_proto_depIdxs,
		MessageInfos:      file_proto_work_proto_msgTypes,
	}.Build()
	File_proto_work_proto = out.File
	file_proto_work_proto_goTypes = nil
	file_proto_work_proto_depIdxs = nil
}
