// The contract between a witness and the machines that verify for it.
//
// This file is the specification. Prose in a README is a poor protocol
// definition for anything a third party might implement, and the point of this
// channel is that other people's machines can join it.
//
// # What a worker is trusted with, which is almost nothing
//
// A worker reports that an epoch verified. It cannot be believed on that alone:
// the operator's signed root is public, so a worker that did no work can still
// report the correct answer. Everything below is shaped by that.
//
//   - Assignments carry a nonce that must be echoed, so a result answers one
//     dispatch and an older honest result cannot be replayed as new work.
//   - Results outside the assigned range are refused.
//   - An expired lease returns its range to the queue with a FRESH nonce, so an
//     abandoned worker's late reply cannot answer the reissue.
//   - Nothing a worker says produces a misbehaviour finding. A disagreement
//     means the witness re-runs the epoch itself, and its own answer decides.
//
// A hostile worker can waste dispatch and inflate a coverage figure until it is
// spot-checked. It cannot make this witness accuse an operator.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: proto/work.proto

package workpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Work_Session_FullMethodName = "/ktwitness.work.v1.Work/Session"
)

// WorkClient is the client API for Work service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Work is one long-lived bidirectional session per worker.
//
// Bidirectional rather than lease-and-submit because the witness should be able
// to push a range the moment one becomes available, and because a worker that
// disappears should be detectable by the stream closing rather than by a lease
// quietly ageing out.
type WorkClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, WitnessMessage], error)
}

type workClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkClient(cc grpc.ClientConnInterface) WorkClient {
	return &workClient{cc}
}

func (c *workClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerMessage, WitnessMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Work_ServiceDesc.Streams[0], Work_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerMessage, WitnessMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Work_SessionClient = grpc.BidiStreamingClient[WorkerMessage, WitnessMessage]

// WorkServer is the server API for Work service.
// All implementations must embed UnimplementedWorkServer
// for forward compatibility.
//
// Work is one long-lived bidirectional session per worker.
//
// Bidirectional rather than lease-and-submit because the witness should be able
// to push a range the moment one becomes available, and because a worker that
// disappears should be detectable by the stream closing rather than by a lease
// quietly ageing out.
type WorkServer interface {
	Session(grpc.BidiStreamingServer[WorkerMessage, WitnessMessage]) error
	mustEmbedUnimplementedWorkServer()
}

// UnimplementedWorkServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkServer struct{}

func (UnimplementedWorkServer) Session(grpc.BidiStreamingServer[WorkerMessage, WitnessMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedWorkServer) mustEmbedUnimplementedWorkServer() {}
func (UnimplementedWorkServer) testEmbeddedByValue()              {}

// UnsafeWorkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkServer will
// result in compilation errors.
type UnsafeWorkServer interface {
	mustEmbedUnimplementedWorkServer()
}

func RegisterWorkServer(s grpc.ServiceRegistrar, srv WorkServer) {
	// If the following call pancis, it indicates UnimplementedWorkServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Work_ServiceDesc, srv)
}

func _Work_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkServer).Session(&grpc.GenericServerStream[WorkerMessage, WitnessMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Work_SessionServer = grpc.BidiStreamingServer[WorkerMessage, WitnessMessage]

// Work_ServiceDesc is the grpc.ServiceDesc for Work service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Work_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ktwitness.work.v1.Work",
	HandlerType: (*WorkServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Work_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/work.proto",
}
