// Package signalaudit replays Signal's key-transparency auditor stream: the
// sequence of AuditorUpdate messages that Signal's Audit RPC hands to its
// third-party auditors (audit.kt.signal.org, mutual TLS with a Signal-issued
// client certificate).
//
// # Why replay rather than sample
//
// The client plane (internal/source/signal) proves the *shape* of Signal's log
// — append-only, one view for everyone — and the full history of the labels we
// can name. It cannot say whether the updates it cannot see were legal, because
// they are hidden behind a VRF on purpose. The auditor stream is the one place
// those updates are shown, each with a proof that it transforms the previous
// prefix tree into the next. Replaying every one of them, from the first, is
// what turns "the log has a consistent shape" into "every change Signal ever
// made to the directory was a legal one".
//
// The state needed for that is tiny — a prefix-tree root and the log frontier,
// well under 2 KiB at a billion entries — because each update carries enough of
// the prefix tree to check itself against the previous root.
//
// # What is checked, and against what
//
// Semantics follow Signal's "Key Transparency Auditor Spec" (May 2025) and
// Trail of Bits' reference auditor (github.com/trailofbits/signal-auditor,
// AGPL-3.0: read for semantics, not copied). Each rule is documented where it
// is enforced; the short version:
//
//   - NewTree is valid only as the very first update, and only real.
//   - DifferentKey proves that a stand-in hash sits where the new index would
//     go (non-inclusion), then replaces it with a fresh leaf (real) or a fresh
//     stand-in (fake).
//   - SameKey proves the existing leaf (inclusion), then bumps its counter,
//     keeping its original position. It is never fake.
//   - The log leaf is SHA-256(new prefix root ‖ commitment), appended to a
//     left-balanced log tree; the commitment is not otherwise checkable.
//
// An update that fails its proof is a contradiction by Signal and is reported as
// a *ProofError; an update that cannot even be read is a *MalformedError. In
// either case the State is left exactly as it was.
//
// # Test vectors
//
// The reference auditor ships test vectors generated by Signal. They are
// AGPL-licensed and so not committed here; fetch them and point the test at
// the file:
//
//	gh api repos/trailofbits/signal-auditor/contents/tests/kt_test_vectors.pb \
//	    --jq .content | base64 -d > /tmp/kt_test_vectors.pb
//	SIGNAL_AUDITOR_VECTORS=/tmp/kt_test_vectors.pb go test ./internal/signalaudit/
//
// (or download https://raw.githubusercontent.com/trailofbits/signal-auditor/main/tests/kt_test_vectors.pb).
package signalaudit

import (
	"fmt"
	"math"

	"github.com/gdbsecurity/kt-witness/internal/pbwire"
)

// Field widths, from the reference (src/lib.rs: Hash and Index are 32 bytes,
// Seed 16) and the spec, which derives a seed as one AES block.
const (
	IndexSize      = 32
	SeedSize       = 16
	CommitmentSize = 32
	HashSize       = 32

	// MaxCopath is the prefix tree's depth. A copath entry exists per level
	// below the root, so no proof can be longer; anything longer would be
	// hashing values that belong to no node.
	MaxCopath = 256
)

// ProofKind is which AuditorProof variant an update carries.
type ProofKind uint8

const (
	NewTree      ProofKind = 1 // AuditorProof.new_tree (field 1)
	DifferentKey ProofKind = 3 // AuditorProof.different_key (field 3)
	SameKey      ProofKind = 4 // AuditorProof.same_key (field 4)
)

func (k ProofKind) String() string {
	switch k {
	case NewTree:
		return "new_tree"
	case DifferentKey:
		return "different_key"
	case SameKey:
		return "same_key"
	}
	return fmt.Sprintf("ProofKind(%d)", uint8(k))
}

// Update is one decoded transparency.AuditorUpdate.
type Update struct {
	// Real is false for the fake updates Signal interleaves to hide the true
	// update rate. A fake update still becomes a log entry.
	Real bool
	// Index is the commitment index (VRF output) — random for a fake update.
	Index [IndexSize]byte
	// Seed derives this entry's stand-in hashes.
	Seed [SeedSize]byte
	// Commitment is bound into the log leaf; random for a fake update.
	Commitment [CommitmentSize]byte

	Proof ProofKind
	// Copath holds sibling hashes root-to-leaf for the explored part of the
	// path: Copath[i] is the sibling at depth i+1, paired with bit i of Index.
	// Empty for NewTree.
	Copath [][HashSize]byte
	// OldSeed (DifferentKey) derives the stand-in being replaced.
	OldSeed [SeedSize]byte
	// Counter and Position (SameKey) describe the existing leaf.
	Counter  uint32
	Position uint64
}

// MalformedError is an update that is not a well-formed AuditorUpdate: bad
// protobuf, a field of the wrong width, or a combination the protocol forbids
// (a fake NewTree, say). Nothing about the tree was consulted.
type MalformedError struct {
	Field  string
	Reason string
}

func (e *MalformedError) Error() string {
	return fmt.Sprintf("signalaudit: malformed update: %s: %s", e.Field, e.Reason)
}

func malformed(field, format string, args ...any) error {
	return &MalformedError{Field: field, Reason: fmt.Sprintf(format, args...)}
}

// DecodeUpdate parses AuditorUpdate wire bytes:
//
//	AuditorUpdate { bool real=1; bytes index=2; bytes seed=3; bytes commitment=4; AuditorProof proof=5 }
//	AuditorProof  { oneof { NewTree new_tree=1; DifferentKey different_key=3; SameKey same_key=4 } }
//	DifferentKey  { repeated bytes copath=1; bytes old_seed=2 }
//	SameKey       { repeated bytes copath=1; uint32 counter=2; uint64 position=3 }
//
// It is stricter than a generic protobuf decoder in three ways, each because
// the decoded fields are the thing being verified rather than a wrapper around
// signed bytes. A known field sent twice is refused rather than resolved
// last-wins, so two parsers can never read one message differently. A known
// field with the wrong wire type is refused rather than skipped. A bool other
// than 0 or 1, or a counter beyond 32 bits, is refused rather than truncated.
// Unknown fields are skipped, as protobuf requires, so Signal can extend the
// message; an unknown *proof* variant leaves the oneof empty and is refused as
// missing, which is the safe direction.
func DecodeUpdate(b []byte) (Update, error) {
	var u Update
	fields, err := pbwire.Fields(b)
	if err != nil {
		return u, malformed("AuditorUpdate", "%v", err)
	}
	var seen [6]bool
	var index, seed, commitment, proof []byte
	for _, f := range fields {
		if f.Num < 1 || f.Num > 5 {
			continue
		}
		name := [...]string{1: "real", 2: "index", 3: "seed", 4: "commitment", 5: "proof"}[f.Num]
		if seen[f.Num] {
			return u, malformed(name, "field appears more than once")
		}
		seen[f.Num] = true
		want := byte(2)
		if f.Num == 1 {
			want = 0
		}
		if f.Wire != want {
			return u, malformed(name, "wire type %d, want %d", f.Wire, want)
		}
		switch f.Num {
		case 1:
			if f.Varint > 1 {
				return u, malformed(name, "bool encoded as %d", f.Varint)
			}
			u.Real = f.Varint == 1
		case 2:
			index = f.Bytes
		case 3:
			seed = f.Bytes
		case 4:
			commitment = f.Bytes
		case 5:
			proof = f.Bytes
		}
	}
	// Absent bytes fields decode as empty under proto3, so a missing field and
	// a short one are the same error.
	if len(index) != IndexSize {
		return u, malformed("index", "%d bytes, want %d", len(index), IndexSize)
	}
	if len(seed) != SeedSize {
		return u, malformed("seed", "%d bytes, want %d", len(seed), SeedSize)
	}
	if len(commitment) != CommitmentSize {
		return u, malformed("commitment", "%d bytes, want %d", len(commitment), CommitmentSize)
	}
	copy(u.Index[:], index)
	copy(u.Seed[:], seed)
	copy(u.Commitment[:], commitment)
	if !seen[5] {
		return u, malformed("proof", "missing")
	}
	if err := decodeProof(proof, &u); err != nil {
		return u, err
	}
	if err := u.validate(); err != nil {
		return u, err
	}
	return u, nil
}

func decodeProof(b []byte, u *Update) error {
	fields, err := pbwire.Fields(b)
	if err != nil {
		return malformed("proof", "%v", err)
	}
	var body []byte
	for _, f := range fields {
		k := ProofKind(f.Num)
		if k != NewTree && k != DifferentKey && k != SameKey {
			continue
		}
		if u.Proof != 0 {
			// Protobuf would let the later member win; Signal's encoder never
			// sends two, so two is a message we would be guessing at.
			return malformed("proof", "both %v and %v present", u.Proof, k)
		}
		if f.Wire != 2 {
			return malformed("proof."+k.String(), "wire type %d, want 2", f.Wire)
		}
		u.Proof, body = k, f.Bytes
	}
	if u.Proof == 0 {
		return malformed("proof", "no new_tree, different_key or same_key")
	}

	name := "proof." + u.Proof.String()
	fields, err = pbwire.Fields(body)
	if err != nil {
		return malformed(name, "%v", err)
	}
	if u.Proof == NewTree {
		return nil // an empty message; anything inside is an unknown field
	}
	var seen [4]bool
	for _, f := range fields {
		switch {
		case f.Num == 1: // copath, both variants
			if f.Wire != 2 {
				return malformed(name+".copath", "wire type %d, want 2", f.Wire)
			}
			if len(f.Bytes) != HashSize {
				return malformed(name+".copath", "entry %d is %d bytes, want %d",
					len(u.Copath), len(f.Bytes), HashSize)
			}
			if len(u.Copath) == MaxCopath {
				return malformed(name+".copath", "more than %d entries", MaxCopath)
			}
			u.Copath = append(u.Copath, [HashSize]byte(f.Bytes))
		case f.Num == 2 && u.Proof == DifferentKey: // old_seed
			if seen[2] {
				return malformed(name+".old_seed", "field appears more than once")
			}
			seen[2] = true
			if f.Wire != 2 || len(f.Bytes) != SeedSize {
				return malformed(name+".old_seed", "wire type %d, %d bytes; want bytes of %d",
					f.Wire, len(f.Bytes), SeedSize)
			}
			u.OldSeed = [SeedSize]byte(f.Bytes)
		case (f.Num == 2 || f.Num == 3) && u.Proof == SameKey: // counter, position
			field := map[int]string{2: ".counter", 3: ".position"}[f.Num]
			if seen[f.Num] {
				return malformed(name+field, "field appears more than once")
			}
			seen[f.Num] = true
			if f.Wire != 0 {
				return malformed(name+field, "wire type %d, want 0", f.Wire)
			}
			if f.Num == 2 {
				if f.Varint > math.MaxUint32 {
					return malformed(name+field, "%d does not fit uint32", f.Varint)
				}
				u.Counter = uint32(f.Varint)
			} else {
				u.Position = f.Varint
			}
		}
	}
	if u.Proof == DifferentKey && !seen[2] {
		return malformed(name+".old_seed", "missing")
	}
	return nil
}

// validate holds the rules that do not depend on the tree. DecodeUpdate runs
// it, and so does Apply, so an Update built by hand gets no laxer treatment
// than one read off the wire.
func (u *Update) validate() error {
	switch u.Proof {
	case NewTree:
		// Spec, "Calculating new prefix tree root hashes / newTree": Signal
		// requires one real update before any fake one, so a fake NewTree is
		// never legitimate. Reference: prefix/mod.rs, TryFrom<AuditorUpdate>.
		if !u.Real {
			return malformed("proof.new_tree", "fake update cannot start the tree")
		}
		if len(u.Copath) != 0 {
			return malformed("proof.new_tree", "carries %d copath entries", len(u.Copath))
		}
	case DifferentKey:
		// The copath ends at the sibling of the stand-in being replaced, so
		// the stand-in sits at depth len(copath). Depth 0 is the root, which
		// is never a stand-in once the tree exists; depth 256 is the leaf
		// level and the deepest a node can be. The reference computes the
		// stand-in level as len-1 and so cannot accept an empty copath either.
		if n := len(u.Copath); n < 1 || n > MaxCopath {
			return malformed("proof.different_key.copath", "%d entries, want 1..%d", n, MaxCopath)
		}
	case SameKey:
		// Spec, "sameKey proofs": only real updates; a real leaf is never
		// replaced by a fake one. Reference: prefix/mod.rs, TryFrom.
		if !u.Real {
			return malformed("proof.same_key", "fake update cannot bump an existing key")
		}
		// An empty copath is legal: it means every sibling is a stand-in from
		// this key's own seed, as when the key is alone in the tree.
		if n := len(u.Copath); n > MaxCopath {
			return malformed("proof.same_key.copath", "%d entries, want at most %d", n, MaxCopath)
		}
	default:
		return malformed("proof", "unknown kind %d", u.Proof)
	}
	return nil
}

// EncodeUpdate is the inverse of DecodeUpdate, in field order with proto3
// defaults omitted — the canonical encoding. Replay never needs it; it exists
// so tests and the offline harness can produce streams without generated code.
func EncodeUpdate(u Update) []byte {
	var b []byte
	if u.Real {
		b = pbwire.AppendTag(b, 1, 0)
		b = pbwire.AppendVarint(b, 1)
	}
	b = appendBytes(b, 2, u.Index[:])
	b = appendBytes(b, 3, u.Seed[:])
	b = appendBytes(b, 4, u.Commitment[:])

	var body []byte
	for _, c := range u.Copath {
		body = appendBytes(body, 1, c[:])
	}
	switch u.Proof {
	case DifferentKey:
		body = appendBytes(body, 2, u.OldSeed[:])
	case SameKey:
		if u.Counter != 0 {
			body = pbwire.AppendTag(body, 2, 0)
			body = pbwire.AppendVarint(body, uint64(u.Counter))
		}
		if u.Position != 0 {
			body = pbwire.AppendTag(body, 3, 0)
			body = pbwire.AppendVarint(body, u.Position)
		}
	}
	proof := appendBytes(nil, int(u.Proof), body)
	return appendBytes(b, 5, proof)
}

func appendBytes(b []byte, field int, v []byte) []byte {
	b = pbwire.AppendTag(b, field, 2)
	b = pbwire.AppendVarint(b, uint64(len(v)))
	return append(b, v...)
}
